apiVersion: v1
kind: Namespace
metadata:
  name: localstack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: localstack
  labels:
    app: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack:latest
        ports:
        - containerPort: 4566
          name: edge
        env:
        - name: SERVICES
          value: "ec2,iam,s3,sts,cloudtrail,guardduty,route53"
        - name: PERSISTENCE
          value: "0"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: localstack
spec:
  type: ClusterIP
  selector:
    app: localstack
  ports:
  - port: 4566
    targetPort: 4566
    name: edge
